version: "3"
services:
  listener:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
  spamer:
    build:
      context: .
      dockerfile: Dockerfile1
    volumes:
      - ".:/app"
